# Generated by Django 5.0.6 on 2024-06-01 14:33

from django.db import migrations

from posts import apps

def populate_status(apps, schemaeditor):
    entries = {
    "draft": "A post that is not ready to be published",
    "published": "A post available for all to see",
    "archived": "An older post available in the archive only"
}

Status = apps.get_model("posts", "Status")
for key, value in entries.items(): # type: ignore
    status_obj = Status(name=key, description=value)
    status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
]

    operations = [migrations.RunPython(populate_status)]